name: Bump stale issues

on:
  workflow_dispatch:

jobs:
  fresh-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Bump stale issues
        uses: ./../action.yml
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Needs `repo` scope
